version: '3.8'

services:
  app:
    container_name: orpos-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: orpos-frontend:latest
    restart: always
    networks:
      - coolify-infra
    labels:
      # --- Traefik Básico ---
      traefik.enable: "true"
      traefik.http.routers.orpos.rule: Host(`orpos.site`) || Host(`www.orpos.site`)
      traefik.http.routers.orpos.entrypoints: websecure
      traefik.http.routers.orpos.tls: "true"
      traefik.http.routers.orpos.tls.certresolver: letsencrypt
      traefik.http.services.orpos.loadbalancer.server.port: 80

      # --- Redirección www -> sin www (opcional, si querés unificar en uno solo) ---
      traefik.http.middlewares.orpos-redirect-www.redirectregex.regex: ^https://www\.(.*)
      traefik.http.middlewares.orpos-redirect-www.redirectregex.replacement: https://$1
      traefik.http.middlewares.orpos-redirect-www.redirectregex.permanent: "true"
      traefik.http.routers.orpos.middlewares: orpos-redirect-www@docker

      # --- Subdominios futuros (heredan configuración base) ---
      # ejemplo: api.orpos.site, admin.orpos.site
      traefik.docker.network: coolify-infra

networks:
  coolify-infra:
    external: true
