version: "3.8"

services:
  orpos-frontend:
    build: .
    container_name: orpos-frontend
    restart: always
    networks:
      - coolify-infra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orpos.rule=Host(`orpos.site`)"
      - "traefik.http.routers.orpos.entrypoints=web"
      - "traefik.http.services.orpos.loadbalancer.server.port=80"

networks:
  coolify-infra:
    external: true
