version: '3.8'

services:
  orpos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      
      # --- MIDDLEWARE ---
      - "traefik.http.middlewares.orpos-redirect-https.redirectscheme.scheme=https"
      
      # --- ROUTER HTTP (¡CON HOSTREGEX!) ---
      - "traefik.http.routers.orpos-frontend-http.rule=Host(`orpos.site`) || Host(`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-http.entrypoints=http"
      - "traefik.http.routers.orpos-frontend-http.middlewares=orpos-redirect-https"

      # --- ROUTER HTTPS (¡CON HOSTREGEX Y DNS-CHALLENGE!) ---
      - "traefik.http.routers.orpos-frontend-secure.rule=Host(`orpos.site`) || Host(`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-secure.entrypoints=https"
      - "traefik.http.routers.orpos-frontend-secure.tls=true"
      - "traefik.http.routers.orpos-frontend-secure.tls.certresolver=letsencrypt-dns" # Volvemos al DNS challenge
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].main=orpos.site"
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].sans=*.orpos.site"
      - "traefik.http.routers.orpos-frontend-secure.service=orpos-frontend-svc"
      
      # --- SERVICE ---
      - "traefik.http.services.orpos-frontend-svc.loadbalancer.server.port=80"

networks:
  coolify:
    external: true