version: '3.8'

services:
  orpos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"

      # --- MIDDLEWARE (Para redirigir a HTTPS) ---
      - "traefik.http.middlewares.orpos-redirect-https.redirectscheme.scheme=https"
      
      # --- ROUTER PARA HTTP (tráfico inseguro) ---
      # Ahora escucha en orpos.site y www.orpos.site, y su única misión es redirigir.
      - "traefik.http.routers.orpos-frontend-http.rule=Host(`orpos.site`) || Host(`www.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-http.entrypoints=http"
      - "traefik.http.routers.orpos-frontend-http.middlewares=orpos-redirect-https"

      # --- ROUTER PARA HTTPS (el principal, seguro) ---
      # Ahora escucha en orpos.site y www.orpos.site.
      - "traefik.http.routers.orpos-frontend-secure.rule=Host(`orpos.site`) || Host(`www.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-secure.entrypoints=https"
      - "traefik.http.routers.orpos-frontend-secure.tls=true"
      - "traefik.http.routers.orpos-frontend-secure.tls.certresolver=letsencrypt" # Seguimos con el challenge HTTP
      - "traefik.http.routers.orpos-frontend-secure.service=orpos-frontend-svc"
      
      # --- SERVICE ---
      - "traefik.http.services.orpos-frontend-svc.loadbalancer.server.port=80"

networks:
  coolify:
    external: true