version: '3.8'

services:
  # --- SERVICIO DE BACKEND ---
  orpos-backend:
    build:
      context: . # El contexto es la raíz del repositorio
      dockerfile: ./backend/Dockerfile # Necesitamos un Dockerfile para el backend
    restart: always
    environment:
      # Coolify leerá estas variables y te permitirá llenarlas como secretos
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.orpos-backend-http.rule=Host(`api.orpos.site`)"
      - "traefik.http.routers.orpos-backend-http.entrypoints=http"
      - "traefik.http.routers.orpos-backend-http.middlewares=https-redirect"
      - "traefik.http.routers.orpos-backend-secure.rule=Host(`api.orpos.site`)"
      - "traefik.http.routers.orpos-backend-secure.entrypoints=https"
      - "traefik.http.routers.orpos-backend-secure.tls=true"
      - "traefik.http.routers.orpos-backend-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.orpos-backend-secure.service=orpos-backend-service"
      - "traefik.http.services.orpos-backend-service.loadbalancer.server.port=3001"

  # --- SERVICIO DE FRONTEND ---
  orpos-frontend:
    build:
      context: .
      dockerfile: Dockerfile # Usa el Dockerfile de la raíz (el que construye el frontend)
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.routers.orpos-frontend-http.rule=Host(`orpos.site`,`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-http.entrypoints=http"
      - "traefik.http.routers.orpos-frontend-http.middlewares=https-redirect"
      - "traefik.http.routers.orpos-frontend-secure.rule=Host(`orpos.site`,`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-secure.entrypoints=https"
      - "traefik.http.routers.orpos-frontend-secure.tls=true"
      - "traefik.http.routers.orpos-frontend-secure.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].main=orpos.site"
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].sans=*.orpos.site"
      - "traefik.http.routers.orpos-frontend-secure.service=orpos-frontend-service"
      - "traefik.http.services.orpos-frontend-service.loadbalancer.server.port=80"
      
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

networks:
  coolify:
    external: true