version: '3.8'

services:
  # --- SERVICIO DE BACKEND ---
  orpos-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    environment:
      # Coolify leerá estas variables y te permitirá llenarlas como secretos
      - "NODE_ENV=production"
      - "PORT=3001"
      - "DB_HOST=${DB_HOST}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_NAME=${DB_NAME}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "FRONTEND_URL=${FRONTEND_URL}"
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # Router HTTP (redirige a HTTPS)
      - "traefik.http.routers.orpos-backend-http.rule=Host(`api.orpos.site`)"
      - "traefik.http.routers.orpos-backend-http.entrypoints=http"
      - "traefik.http.routers.orpos-backend-http.middlewares=https-redirect"

      # Router HTTPS principal (NO especificamos 'service')
      - "traefik.http.routers.orpos-backend-secure.rule=Host(`api.orpos.site`)"
      - "traefik.http.routers.orpos-backend-secure.entrypoints=https"
      - "traefik.http.routers.orpos-backend-secure.tls=true"
      - "traefik.http.routers.orpos-backend-secure.tls.certresolver=letsencrypt"

      # El servicio se define implícitamente por el puerto del contenedor.
      # No necesitamos la línea `loadbalancer.server.port` porque solo hay uno.

  # --- SERVICIO DE FRONTEND ---
  orpos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

      # Router HTTP (redirige a HTTPS)
      - "traefik.http.routers.orpos-frontend-http.rule=Host(`orpos.site`,`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-http.entrypoints=http"
      - "traefik.http.routers.orpos-frontend-http.middlewares=https-redirect"
      
      # Router HTTPS principal (NO especificamos 'service')
      - "traefik.http.routers.orpos-frontend-secure.rule=Host(`orpos.site`,`www.orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-frontend-secure.entrypoints=httpss"
      - "traefik.http.routers.orpos-frontend-secure.tls=true"
      - "traefik.http.routers.orpos-frontend-secure.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].main=orpos.site"
      - "traefik.http.routers.orpos-frontend-secure.tls.domains[0].sans=*.orpos.site"

      # Middleware de redirección (definido en este servicio para evitar conflictos)
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      
# Definimos la red a la que se deben conectar, que debe ser la red del proxy de Coolify
networks:
  coolify:
    external: true