version: '3.8'

services:
  app:
    container_name: orpos-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: orpos-frontend:latest
    restart: always
    networks:
      - coolify
    labels:
      traefik.enable: "true"
      traefik.docker.network: coolify

      # --- Router principal 2 ---
      traefik.http.routers.orpos.rule: Host(`orpos.site`) || HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)
      traefik.http.routers.orpos.entrypoints: https
      traefik.http.routers.orpos.tls: "true"
      traefik.http.routers.orpos.tls.certresolver: letsencrypt
      traefik.http.services.orpos.loadbalancer.server.port: 80

networks:
  coolify:
    external: true
