version: '3.8'

services:
  orpos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"

      # --- ROUTER MINIMALISTA ---
      # Solo escucha en el dominio principal, sin subdominios, sin www, sin redirección.
      - "traefik.http.routers.orpos-frontend.rule=Host(`orpos.site`)"
      - "traefik.http.routers.orpos-frontend.entrypoints=https"
      - "traefik.http.routers.orpos-frontend.tls=true"
      - "traefik.http.routers.orpos-frontend.tls.certresolver=letsencrypt" # Usamos el HTTP challenge normal
      - "traefik.http.routers.orpos-frontend.service=orpos-frontend-svc"
      
      # --- SERVICE MINIMALISTA ---
      - "traefik.http.services.orpos-frontend-svc.loadbalancer.server.port=80"

networks:
  coolify:
    external: true