version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: orpos-frontend:latest
    container_name: orpos-frontend
    restart: always
    networks:
      - coolify-infra
    labels:
      - "traefik.enable=true"

      # dominio principal
      - "traefik.http.routers.orpos.rule=Host(`orpos.site`)"
      - "traefik.http.routers.orpos.entrypoints=https"
      - "traefik.http.routers.orpos.tls=true"
      - "traefik.http.routers.orpos.tls.certresolver=letsencrypt"

      # wildcard
      - "traefik.http.routers.orpos-wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.orpos.site`)"
      - "traefik.http.routers.orpos-wildcard.entrypoints=https"
      - "traefik.http.routers.orpos-wildcard.tls=true"
      - "traefik.http.routers.orpos-wildcard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.orpos-wildcard.service=orpos"

      # servicio compartido
      - "traefik.http.services.orpos.loadbalancer.server.port=80"

networks:
  coolify-infra:
    external: true
